(defun c:addattrib ( blk )
   (while
       (not
           (or (= "" (setq blk (getstring t "\nName of block to update: ")))
               (tblsearch "BLOCK" blk)
           )
       )
       (princ (strcat "\nBlock \"" blk "\" not found."))
   )
   (if (/= "" blk)
       (progn
           (vla-addattribute
               (vla-item (vla-get-blocks (vla-get-activedocument (vlax-get-acad-object))) blk)
               (getvar 'textsize)
               acattributemodelockposition
               "New Attribute"
               (vlax-3D-point 0 0)
               "NEW_TAG"
               "New Value"
           )
           (command "_.attsync" "_N" blk)
       )
   )
   (princ)
)
(vl-load-com) (princ)
